# Generated by Django 6.0.1 on 2026-02-01 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Video')),
                ('slug', models.SlugField(help_text='ID único (ej: blackrock-empire)', unique=True)),
                ('status', models.CharField(choices=[('IDEA', '💡 Idea / Borrador'), ('SCRIPTING', '📝 Guion Listo'), ('RENDERING', '⚙️ Renderizando'), ('DONE', '✅ Terminado'), ('UPLOADED', '🚀 Subido a YouTube')], default='IDEA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('narration_text', models.TextField(verbose_name='Texto Narración (TTS)')),
                ('visual_prompt', models.TextField(verbose_name='Prompt para Vertex AI')),
                ('overlay_text', models.CharField(blank=True, max_length=100, verbose_name='Texto en Pantalla (Opcional)')),
                ('effect_type', models.CharField(choices=[('ZOOM_SLOW', '🔍 Zoom Lento (Ken Burns)'), ('ZOOM_FAST', '⚡ Zoom Agresivo (Gancho)'), ('PARTICLES_GOLD', '✨ Partículas Doradas'), ('MONEY_RAIN', '💸 Lluvia de Dinero'), ('STATIC', '🛑 Estático')], default='ZOOM_SLOW', max_length=50)),
                ('duration', models.IntegerField(default=5, verbose_name='Duración (seg)')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='core.videoproject')),
            ],
            options={
                'verbose_name': 'Escena',
                'verbose_name_plural': 'Escenas',
                'ordering': ['order'],
            },
        ),
    ]
